import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load pre‑computed forecast samples generated by 04_sample_and_baseline.py
samples_df = pd.read_parquet("../data/processed/forecast_samples.parquet")
print(f"Loaded total forecast samples: {len(samples_df)}")

# --------------------------
# Re‑compute Persistence Baseline metrics
# --------------------------
samples_df["lon_pred_persistence"] = samples_df["lon_current"]
samples_df["lat_pred_persistence"] = samples_df["lat_current"]
samples_df["lon_error"] = samples_df["lon_pred_persistence"] - samples_df["lon_true_24h"]
samples_df["lat_error"] = samples_df["lat_pred_persistence"] - samples_df["lat_true_24h"]
samples_df["pos_error_deg"] = np.sqrt(samples_df["lon_error"] ** 2 + samples_df["lat_error"] ** 2)

# --------------------------
# Constant‑Advection Baseline
# Predict future position using current velocity for full 24‑hour window
# --------------------------
seconds_24h = 24 * 3600
meters_per_degree = 111000  # approximate 1 degree ≈ 111 km on Earth surface

samples_df["lon_pred_adv"] = (
    samples_df["lon_current"]
    + samples_df["ve_current"] * seconds_24h / meters_per_degree
)
samples_df["lat_pred_adv"] = (
    samples_df["lat_current"]
    + samples_df["vn_current"] * seconds_24h / meters_per_degree
)

# Calculate position error
samples_df["lon_error_adv"] = samples_df["lon_pred_adv"] - samples_df["lon_true_24h"]
samples_df["lat_error_adv"] = samples_df["lat_pred_adv"] - samples_df["lat_true_24h"]
samples_df["pos_error_adv_deg"] = np.sqrt(
    samples_df["lon_error_adv"] ** 2 + samples_df["lat_error_adv"] ** 2
)

mean_persist_error = samples_df["pos_error_deg"].mean()
median_persist_error = samples_df["pos_error_deg"].median()
mean_adv_error = samples_df["pos_error_adv_deg"].mean()
median_adv_error = samples_df["pos_error_adv_deg"].median()

print("\n======== Persistence Baseline Result ========")
print(f"Mean position error (degrees):   {mean_persist_error:.4f}")
print(f"Median position error (degrees): {median_persist_error:.4f}")

print("\n======== Constant‑Advection Baseline Result ========")
print(f"Mean position error (degrees):   {mean_adv_error:.4f}")
print(f"Median position error (degrees): {median_adv_error:.4f}")

print("\n-------- Compare two baselines --------")
print(f"Persistence     mean error: {mean_persist_error:.4f} deg")
print(f"Constant‑Advection mean error: {mean_adv_error:.4f} deg")

# Plot error distribution comparison
plt.figure(figsize=(9, 5))
plt.hist(
    samples_df["pos_error_deg"],
    bins=80, range=(0, 2), alpha=0.6,
    label="Persistence Baseline", density=True
)
plt.hist(
    samples_df["pos_error_adv_deg"],
    bins=80, range=(0, 2), alpha=0.6,
    label="Constant‑Advection Baseline", density=True
)
plt.title("24‑h Forecast Error Distribution: Two Baselines Comparison")
plt.xlabel("Position Error (degrees)")
plt.ylabel("Density")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("../image/baselines_comparison.png", dpi=150)
plt.close()

print("\nComparison figure saved to ../image/baselines_comparison.png")
